### ISSUE TITLE
Develop Driver for LCD

### ISSUE THREAD

**Issue by RetoFreivogel** [TheComet93/bat6#20]

**Comment by TheComet** [comment]
We're using the I2C interface.

Here's the [link to Digikey](http://www.digikey.com/product-search/en?keywords=NHD-0420CW-AR3-ND)

Here's the pin-out:
![pin-out](http://i.imgur.com/OuxPsaN.jpg)

**Note**: Configure those 3 pins as open collector (pull-ups are connected to 5V externally).
