### ISSUE TITLE
develop control algorithm for output regulation

### ISSUE THREAD

**Issue by RetoFreivogel** [TheComet93/bat6#23]

**Comment by TheComet** [comment]
**Note**: RC filters to and from the buck regulator are set at f0=5kHz. To be safe we should operate well under that frequency.

**Comment by RetoFreivogel** [comment]
Its quite a mess right now and probably full of bugs. I will rewrite it using the fixed point lib from mplab, hopefully this will not use to much memory. Current Memory use:
Program Memory  0xd4d  (3405) 21%
Data Memory     0x21c  (540) 26%
