### ISSUE TITLE
Configure UART hardware

### ISSUE THREAD

**Issue by TheComet** [TheComet93/bat6#68]
Suggest the following things
- 1 start bit, 1 stop bit
- 1 parity bit (even parity)
- Flow control: None required
- Baud rate: 38'400

Keep in mind: TX and RX are inverted signals because of the galvanic isolation

**Comment by alpenwasser** [comment]
So far only anal rapage is occurring.

General link collection:
http://www.embeddedcodesource.com/search?searchterm=uart&type=all
https://gist.github.com/BETHEBLUES/bad5429c91648b1107c4
https://github.com/search?p=3&q=uart+pic&ref=searchresults&type=Repositories&utf8=%E2%9C%93
https://github.com/digibird1/PICkit2_WithMPLabX/blob/master/Code/UART.h
https://github.com/kcaluwae/dspic33e-bootloader/tree/master/dspic_bootloader
https://github.com/jason6502/pic-uart/blob/master/pic-uart.c
https://github.com/ibexuk/C_Communications_UART_PIC32_Full_Duplex/blob/master/ap-comms.c
