### ISSUE TITLE
What does bat6 mean anyway

### ISSUE THREAD

**Issue by TheComet** [TheComet93/bat6#73]
Current ideas
- Baseball bat
- Bats? Because ultrasonic
- Battery Absent Transformer

**Comment by alpenwasser** [comment]
We like bats (the animals), and this was the sixth name we came up with? Or the sixth `<something else>`?

**Comment by TheComet** [comment]
I like the bats idea. I think we should go with that.

And if anyone tries to imply something we just act all innocent.

**Comment by alpenwasser** [comment]
Sounds good to me.

**Comment by TheComet** [comment]
6 as in a bat's 6th sense
