### ISSUE TITLE
UART: CTS

### ISSUE THREAD

**Issue by alpenwasser** [TheComet93/bat6#78]
Temporarily assigned to RC10/RP58. Fix once design finalised.

Files affected so far:
- hw.h
- uart.c

Also:
Temporarily assigned RTS to RC13/RP61

**Comment by TheComet** [comment]
After further investigation, there's no burning need to support this feature.
- Routing the RTS/CTS wires would require a second isolation IC which we don't have.
- Our protocol doesn't necessarily even need this mechanism.
- If we really do need to dynamically control throughput rates, it is also possible to do this on top of the existing protocol by sending special sequences that don't get stored in the receive/send queue but instead get directly processed by the interrupt. Chances are we won't need this though.

Based on these points, this issue will not be fixed.
